// Share tokens are generated by the backend as random slugs drawn from
// [a-zA-Z0-9]. Keep this permissive enough for any reasonable token while
// still rejecting obviously invalid input (whitespace, slashes, etc.).
const BARE_SLUG_RE = /^[A-Za-z0-9_-]+$/

/**
 * Extract a share token from arbitrary user input.
 *
 * Accepts, in order of preference:
 *  1. A full share URL (web path-based `https://host/s/<token>` or Tauri
 *     hash-based `https://host/#/s/<token>`).
 *  2. A bare path fragment such as `/s/<token>`.
 *  3. A bare slug code such as `aB3xY9...`.
 *
 * Returns the token string, or `null` when the input cannot be resolved to a
 * token.
 */
export function parseShareToken(input: string): string | null {
  const trimmed = input.trim()
  if (!trimmed) return null

  // 1. Try parsing as a full URL first.
  try {
    const url = new URL(trimmed)

    // Hash-based route format (Tauri desktop app): #/s/{shareToken}
    if (url.hash) {
      const hashMatch = url.hash.match(/#\/s\/([^/?#]+)/)
      if (hashMatch?.[1]) return hashMatch[1]
    }

    // Path-based route format (web): /s/{shareToken}
    const pathMatch = url.pathname.match(/\/s\/([^/?#]+)/)
    if (pathMatch?.[1]) return pathMatch[1]
  } catch {
    // Not an absolute URL — fall through to the path/slug handlers below.
  }

  // 2. Relative path fragment: /s/<token>
  const fragmentMatch = trimmed.match(/\/s\/([^/?#]+)/)
  if (fragmentMatch?.[1]) return fragmentMatch[1]

  // 3. Bare slug code.
  if (BARE_SLUG_RE.test(trimmed)) return trimmed

  return null
}
